apiVersion: v1
kind: Service
metadata:
  name: result-servce
  labels:
    name: result-service
    app: demo-voting-app
spec:
  type: LoadBalancer
  ports:
   - port: 80
     targetPort: 90
  selector:
    name: result-app-pod
    app: demo-voting-app