apiVersion: v1
kind: Service
metadata:
  name: voting-servce
  labels:
    name: voting-service
    app: demo-voting-app
spec:
  type: LoadBalancer
  ports:
   - port: 80
     targetPort: 90
  selector:
    name: voting-app-pod
    app: demo-voting-app